# -*- coding: utf-8 -*-
"""Ejercicio_Integración_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A8KHZTbR8XgpNo1jbcwhM9eE6Ky_7jAh
"""

import numpy as np
import matplotlib.pyplot as plt


n = 1000
x = np.linspace(-1,1,n+1)
y = np.linspace(-1,1,n+1)

def esfera(x,y):

  R = 1

  z = R**2 - x**2 - y**2

  if z < 0:
    return 0
  else:
    return np.sqrt(z)

esfera = np.vectorize(esfera)

x_mesh,y_mesh = np.meshgrid(x,y)

z_mesh = esfera(x_mesh,y_mesh)


#---------------------------------------

V = 0

area = (x[1]-x[0])**2

for i in range(len(z_mesh)-1):

    for j in range(len(x_mesh)-1):

        Prom=(z_mesh[i,j]+z_mesh[i+1,j]+z_mesh[i,j+1]+z_mesh[i+1,j+1])/4

        V += Prom * area

print(V)

fig = plt.figure()
ax = fig.add_subplot(111,projection='3d')
ax.plot_surface(x_mesh,y_mesh,z_mesh)