# -*- coding: utf-8 -*-
"""Ejercicio_Integración_10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5bCN2yCUFgOtOLO68HvDtMP5bdRFGbt
"""

import sympy as sym

x = sym.symbols("x")
h = sym.symbols("h")
f = sym.symbols("f")
z = sym.symbols("z")

func = (x)*(x-h)*(x-2*h)*(x-3*h)
int_indef = sym.integrate(func,x)
int_def = (int_indef.subs(x,3*h) - int_indef.subs(x,0)) * ((f**4*(z))/(4*3*2*1))

int_def